language: java

jdk:
  - openjdk8

addons:
  apt:
    packages:
    - graphviz
    - libalut0
    - dbus-x11
    - tidy
    - pulseaudio-module-x11
  firefox: latest
  chrome: beta
  sonarcloud:
    organization: "mickster04"
    token:
      secure: "Rtq1nu+inR87zPwlGq+ABKAPErfGpM9NXK3RAe2lhqT4Uktn3VeEcEZ4HNPeM0+a/QawnsTF2B8Aok3wQM4psgLCIrWeqaEWkiOeNzWrAN1lvZr+r3tHWFl4/q3y0CQrk8N8nsuCdH+1ntd1f97ODfs9t/6Ee65YAGhyeTVVx4gHYDJrJbN3qqAFIeHL8mOiEEKWzUD0ZoEN3GUhHGku238BLUYc+1itFbpruhoD5uMTIarD75njWcBy5+DLIexBZcg892m06vL5TrHDiv3XYdcNwCHjV3qtDb8tdRNpAqk0fJi+j9jNgws+/mf4lqpfM9AQC9U1uT6FfPPxx+lDUM8u3GCqLh41jlpdxr/RwqkNdsFKBUPfzPxG8FelzOkLr96AcMcuo+m+WEAea71cGKVUnxsFVPzHridrOav+7dfKfd7XMSJ0u1OFfa/E1PcAWk42hqippt7ulMbctZ93+0adFXTCIaQClDbc1jhiRjyw2eD22RtzRkTGhg4BGzaKg61vIG2foGfzzI+oddxgeDvVWWEW8ig3y/KVvZzni2ZEMbMOzPIFzU5FZFmcT0qjI98B8M8q6+B5HnebfMukjLkffD/oJ3B3/zmW26XRL0y31A58vzTezhCqZM/fy2Fo/eemg5fH6XXhkfT9Qmatz2yZNtsbIbKxQBQXX4ghMcA=" # encrypted value of your token
services:
  - xvfb

before_install:
  # ensure no unwanted defaults are set
  # see https://github.com/travis-ci/travis-ci/issues/4613#issuecomment-181845546
  - export MAVEN_SKIP_RC="true"
  # install graphviz on macOS
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz ; fi

install:
  - mvn verify -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before_script:
  # start audio services
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then start-pulseaudio-x11 ; fi
  # silence errors from firefox about dbus.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dbus-launch ; fi

script:
  - sonar-scanner -Dsonar.projectKey=mickster04_JMRI -Dsonar.projectVersion=1.3
  #- mvn clean verify
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - if [[ "$PRINT_SUMMARY" == "false" ]] ; then travis_wait 50 ./scripts/travis.sh ; else ./scripts/travis.sh ; fi

git:
  depth: false

cache:
  directories:
  - $HOME/.m2

os:
  - linux
#  - osx # temporarilly disabled -- its more complex than originally anticipated to do conditional matrixes based on PR/push differentiation

dist: xenial

sudo: required

env:
  global:
  # false to silence most maven output; true to catch tests that do not complete
  - PRINT_SUMMARY=true
  - MAVEN_OPTS=-Xmx1536m
  # see http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#runOrder for valid values
  - RUN_ORDER=filesystem
  matrix:
  - HEADLESS=false STATIC=false
  - HEADLESS=true STATIC=false
  - HEADLESS=true STATIC=true

matrix:
  exclude:
  - os: osx
    env: HEADLESS=true STATIC=true
  - os: osx
    env: HEADLESS=true STATIC=false

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$HEADLESS" == "false" ]] ; then mvn jacoco:report coveralls:report -U -P travis-coverage ; fi
